github:
  client:
    id: c87130fde60ed50407e2
    secret: 9eeefa60de0f3b9f49749c60be12d11be15bec51
  redirect:
    uri: http://localhost:8080/callback

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zjwhayafd123
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.zjw.community.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true